// Hybrid AI + original-art covers for every non-PC catalog title.
window.HYBRID_COVERS = Object.freeze({
  ".hack//G.U. Last Recode": "assets/covers/hybrid/catalog/hack-g-u-last-recode.webp",
  "Actraiser Renaissance": "assets/covers/hybrid/catalog/actraiser-renaissance.webp",
  "Atelier Ryza: Ever Darkness & the Secret Hideout DX": "assets/covers/hybrid/catalog/atelier-ryza-ever-darkness-the-secret-hideout-dx.webp",
  "Atelier Ryza 2: Lost Legends & the Secret Fairy DX": "assets/covers/hybrid/catalog/atelier-ryza-2-lost-legends-the-secret-fairy-dx.webp",
  "Atelier Ryza 3: Alchemist of the End & the Secret Key DX": "assets/covers/hybrid/catalog/atelier-ryza-3-alchemist-of-the-end-the-secret-key-dx.webp",
  "Blaster Master Zero": "assets/covers/hybrid/catalog/blaster-master-zero.webp",
  "Blossom Tales: The Sleeping King": "assets/covers/hybrid/catalog/blossom-tales-the-sleeping-king.webp",
  "Brave Dungeon": "assets/covers/hybrid/catalog/brave-dungeon.webp",
  "Children of Morta": "assets/covers/hybrid/catalog/children-of-morta.webp",
  "Code of Princess EX": "assets/covers/hybrid/catalog/code-of-princess-ex.webp",
  "Crypt of the NecroDancer: Nintendo Switch Edition": "assets/covers/hybrid/catalog/crypt-of-the-necrodancer-nintendo-switch-edition.webp",
  "Dark Witch's Story: COMBAT": "assets/covers/hybrid/catalog/dark-witch-s-story-combat.webp",
  "Darksiders Genesis": "assets/covers/hybrid/catalog/darksiders-genesis.webp",
  "Dead Cells": "assets/covers/hybrid/catalog/dead-cells.webp",
  "Diablo III: Eternal Collection": "assets/covers/hybrid/catalog/diablo-iii-eternal-collection.webp",
  "DRAGON BALL XENOVERSE 2": "assets/covers/hybrid/catalog/dragon-ball-xenoverse-2.webp",
  "DRAGON BALL Z: KAKAROT + A NEW POWER AWAKENS SET": "assets/covers/hybrid/catalog/dragon-ball-z-kakarot-a-new-power-awakens-set.webp",
  "DRAGON QUEST XI S: Echoes of an Elusive Age - Definitive Edition": "assets/covers/hybrid/catalog/dragon-quest-xi-s-echoes-of-an-elusive-age-definitive-edition.webp",
  "DragonFangZ - The Rose & Dungeon of Time": "assets/covers/hybrid/catalog/dragonfangz-the-rose-dungeon-of-time.webp",
  "FANTASY LIFE i: The Girl Who Steals Time Nintendo Switch 2 Edition": "assets/covers/hybrid/catalog/fantasy-life-i-the-girl-who-steals-time-nintendo-switch-2-edition.webp",
  "FINAL FANTASY": "assets/covers/hybrid/catalog/final-fantasy.webp",
  "FINAL FANTASY II": "assets/covers/hybrid/catalog/final-fantasy-ii.webp",
  "FINAL FANTASY III": "assets/covers/hybrid/catalog/final-fantasy-iii.webp",
  "FINAL FANTASY IV": "assets/covers/hybrid/catalog/final-fantasy-iv.webp",
  "FINAL FANTASY V": "assets/covers/hybrid/catalog/final-fantasy-v.webp",
  "FINAL FANTASY VI": "assets/covers/hybrid/catalog/final-fantasy-vi.webp",
  "FINAL FANTASY VII": "assets/covers/hybrid/catalog/final-fantasy-vii.webp",
  "Goblin Sword": "assets/covers/hybrid/catalog/goblin-sword.webp",
  "Guardian Tales": "assets/covers/hybrid/catalog/guardian-tales.webp",
  "Hello Neighbor": "assets/covers/hybrid/catalog/hello-neighbor.webp",
  "Hyrule Warriors: Definitive Edition": "assets/covers/hybrid/catalog/hyrule-warriors-definitive-edition.webp",
  "I Am Setsuna": "assets/covers/hybrid/catalog/i-am-setsuna.webp",
  "Langrisser I & II": "assets/covers/hybrid/catalog/langrisser-i-ii.webp",
  "Mario + Rabbids Kingdom Battle": "assets/covers/hybrid/catalog/mario-rabbids-kingdom-battle.webp",
  "Mega Man Zero/ZX Legacy Collection": "assets/covers/hybrid/catalog/mega-man-zero-zx-legacy-collection.webp",
  "Miden Tower": "assets/covers/hybrid/catalog/miden-tower.webp",
  "MIGHTY GUNVOLT BURST": "assets/covers/hybrid/catalog/mighty-gunvolt-burst.webp",
  "Minecraft": "assets/covers/hybrid/catalog/minecraft.webp",
  "Minecraft Dungeons": "assets/covers/hybrid/catalog/minecraft-dungeons.webp",
  "Nine Parchments": "assets/covers/hybrid/catalog/nine-parchments.webp",
  "OCTOPATH TRAVELER": "assets/covers/hybrid/catalog/octopath-traveler.webp",
  "Paper Mario: The Origami King": "assets/covers/hybrid/catalog/paper-mario-the-origami-king.webp",
  "PixARK": "assets/covers/hybrid/catalog/pixark.webp",
  "Pokémon Shield": "assets/covers/hybrid/catalog/pokemon-shield.webp",
  "Record of Lodoss War-Deedlit in Wonder Labyrinth-": "assets/covers/hybrid/catalog/record-of-lodoss-war-deedlit-in-wonder-labyrinth.webp",
  "Resident Evil Revelations": "assets/covers/hybrid/catalog/resident-evil-revelations.webp",
  "Resident Evil Revelations 2": "assets/covers/hybrid/catalog/resident-evil-revelations-2.webp",
  "Rogue Legacy 2": "assets/covers/hybrid/catalog/rogue-legacy-2.webp",
  "Romancing SaGa 2": "assets/covers/hybrid/catalog/romancing-saga-2.webp",
  "Ruinverse": "assets/covers/hybrid/catalog/ruinverse.webp",
  "Shovel Knight: Treasure Trove": "assets/covers/hybrid/catalog/shovel-knight-treasure-trove.webp",
  "Sonic Mania": "assets/covers/hybrid/catalog/sonic-mania.webp",
  "Super Mario 64": "assets/covers/hybrid/catalog/super-mario-64.webp",
  "Super Mario Galaxy": "assets/covers/hybrid/catalog/super-mario-galaxy.webp",
  "Super Mario Maker 2": "assets/covers/hybrid/catalog/super-mario-maker-2.webp",
  "Super Mario Sunshine": "assets/covers/hybrid/catalog/super-mario-sunshine.webp",
  "Tetris 99": "assets/covers/hybrid/catalog/tetris-99.webp",
  "Valthirian Arc: Hero School Story": "assets/covers/hybrid/catalog/valthirian-arc-hero-school-story.webp",
  "Xenoblade Chronicles 2": "assets/covers/hybrid/catalog/xenoblade-chronicles-2.webp",
  "Adventures of Lolo": "assets/covers/hybrid/catalog/adventures-of-lolo.webp",
  "Balloon Fight": "assets/covers/hybrid/catalog/balloon-fight.webp",
  "Baseball": "assets/covers/hybrid/catalog/baseball.webp",
  "Battletoads": "assets/covers/hybrid/catalog/battletoads.webp",
  "Blaster Master": "assets/covers/hybrid/catalog/blaster-master.webp",
  "City Connection": "assets/covers/hybrid/catalog/city-connection.webp",
  "Clu Clu Land": "assets/covers/hybrid/catalog/clu-clu-land.webp",
  "Cobra Triangle": "assets/covers/hybrid/catalog/cobra-triangle.webp",
  "Crystalis": "assets/covers/hybrid/catalog/crystalis.webp",
  "Daiva Story 6: Imperial of Nirsartia": "assets/covers/hybrid/catalog/daiva-story-6-imperial-of-nirsartia.webp",
  "Devil World": "assets/covers/hybrid/catalog/devil-world.webp",
  "Dig Dug II": "assets/covers/hybrid/catalog/dig-dug-ii.webp",
  "Donkey Kong": "assets/covers/hybrid/catalog/donkey-kong.webp",
  "Donkey Kong 3": "assets/covers/hybrid/catalog/donkey-kong-3.webp",
  "Donkey Kong Jr.": "assets/covers/hybrid/catalog/donkey-kong-jr.webp",
  "Donkey Kong Jr. Math": "assets/covers/hybrid/catalog/donkey-kong-jr-math.webp",
  "Double Dragon": "assets/covers/hybrid/catalog/double-dragon.webp",
  "Double Dragon II: The Revenge": "assets/covers/hybrid/catalog/double-dragon-ii-the-revenge.webp",
  "Downtown Nekketsu March: Super-Awesome Field Day!": "assets/covers/hybrid/catalog/downtown-nekketsu-march-super-awesome-field-day.webp",
  "Dr. Mario": "assets/covers/hybrid/catalog/dr-mario.webp",
  "EarthBound Beginnings": "assets/covers/hybrid/catalog/earthbound-beginnings.webp",
  "Eliminator Boat Duel": "assets/covers/hybrid/catalog/eliminator-boat-duel.webp",
  "Excitebike": "assets/covers/hybrid/catalog/excitebike.webp",
  "Fire 'n Ice": "assets/covers/hybrid/catalog/fire-n-ice.webp",
  "Ghosts 'n Goblins": "assets/covers/hybrid/catalog/ghosts-n-goblins.webp",
  "Golf": "assets/covers/hybrid/catalog/golf.webp",
  "Gradius": "assets/covers/hybrid/catalog/gradius.webp",
  "Ice Climber": "assets/covers/hybrid/catalog/ice-climber.webp",
  "Ice Hockey": "assets/covers/hybrid/catalog/ice-hockey.webp",
  "Journey to Silius": "assets/covers/hybrid/catalog/journey-to-silius.webp",
  "Joy Mech Fight": "assets/covers/hybrid/catalog/joy-mech-fight.webp",
  "Kid Icarus": "assets/covers/hybrid/catalog/kid-icarus.webp",
  "Kirby's Adventure": "assets/covers/hybrid/catalog/kirby-s-adventure.webp",
  "Kung-Fu Heroes": "assets/covers/hybrid/catalog/kung-fu-heroes.webp",
  "Mach Rider": "assets/covers/hybrid/catalog/mach-rider.webp",
  "Mappy-Land": "assets/covers/hybrid/catalog/mappy-land.webp",
  "Mario Bros.": "assets/covers/hybrid/catalog/mario-bros.webp",
  "Mendel Palace": "assets/covers/hybrid/catalog/mendel-palace.webp",
  "Metroid": "assets/covers/hybrid/catalog/metroid.webp",
  "Mighty Bomb Jack": "assets/covers/hybrid/catalog/mighty-bomb-jack.webp",
  "Mystery Tower": "assets/covers/hybrid/catalog/mystery-tower.webp",
  "NES Open Tournament Golf": "assets/covers/hybrid/catalog/nes-open-tournament-golf.webp",
  "Nightshade": "assets/covers/hybrid/catalog/nightshade.webp",
  "Ninja Gaiden": "assets/covers/hybrid/catalog/ninja-gaiden.webp",
  "Ninja Gaiden II: The Dark Sword of Chaos": "assets/covers/hybrid/catalog/ninja-gaiden-ii-the-dark-sword-of-chaos.webp",
  "Ninja JaJaMaru-kun": "assets/covers/hybrid/catalog/ninja-jajamaru-kun.webp",
  "Pac-Man": "assets/covers/hybrid/catalog/pac-man.webp",
  "Pinball": "assets/covers/hybrid/catalog/pinball.webp",
  "Pro Wrestling": "assets/covers/hybrid/catalog/pro-wrestling.webp",
  "Punch-Out!!": "assets/covers/hybrid/catalog/punch-out.webp",
  "R.C. Pro-Am": "assets/covers/hybrid/catalog/r-c-pro-am.webp",
  "River City Ransom": "assets/covers/hybrid/catalog/river-city-ransom.webp",
  "Rygar": "assets/covers/hybrid/catalog/rygar.webp",
  "S.C.A.T.: Special Cybernetic Attack Team": "assets/covers/hybrid/catalog/s-c-a-t-special-cybernetic-attack-team.webp",
  "Shadow of the Ninja": "assets/covers/hybrid/catalog/shadow-of-the-ninja.webp",
  "Snake Rattle 'n' Roll": "assets/covers/hybrid/catalog/snake-rattle-n-roll.webp",
  "Soccer": "assets/covers/hybrid/catalog/soccer.webp",
  "Solar Jetman": "assets/covers/hybrid/catalog/solar-jetman.webp",
  "Solomon's Key": "assets/covers/hybrid/catalog/solomon-s-key.webp",
  "Star Soldier": "assets/covers/hybrid/catalog/star-soldier.webp",
  "StarTropics": "assets/covers/hybrid/catalog/startropics.webp",
  "Super Dodge Ball": "assets/covers/hybrid/catalog/super-dodge-ball.webp",
  "Super Mario Bros.": "assets/covers/hybrid/catalog/super-mario-bros.webp",
  "Super Mario Bros. 2": "assets/covers/hybrid/catalog/super-mario-bros-2.webp",
  "Super Mario Bros. 3": "assets/covers/hybrid/catalog/super-mario-bros-3.webp",
  "Super Mario Bros.: The Lost Levels": "assets/covers/hybrid/catalog/super-mario-bros-the-lost-levels.webp",
  "Tecmo Bowl": "assets/covers/hybrid/catalog/tecmo-bowl.webp",
  "Tennis": "assets/covers/hybrid/catalog/tennis.webp",
  "Tetris": "assets/covers/hybrid/catalog/tetris.webp",
  "The Immortal": "assets/covers/hybrid/catalog/the-immortal.webp",
  "The Legend of Zelda": "assets/covers/hybrid/catalog/the-legend-of-zelda.webp",
  "The Mysterious Murasame Castle": "assets/covers/hybrid/catalog/the-mysterious-murasame-castle.webp",
  "The Mystery of Atlantis": "assets/covers/hybrid/catalog/the-mystery-of-atlantis.webp",
  "The Tower of Druaga": "assets/covers/hybrid/catalog/the-tower-of-druaga.webp",
  "TwinBee": "assets/covers/hybrid/catalog/twinbee.webp",
  "Urban Champion": "assets/covers/hybrid/catalog/urban-champion.webp",
  "Vice: Project Doom": "assets/covers/hybrid/catalog/vice-project-doom.webp",
  "Volleyball": "assets/covers/hybrid/catalog/volleyball.webp",
  "Vs. Excitebike": "assets/covers/hybrid/catalog/vs-excitebike.webp",
  "Wario's Woods": "assets/covers/hybrid/catalog/wario-s-woods.webp",
  "Wrecking Crew": "assets/covers/hybrid/catalog/wrecking-crew.webp",
  "Xevious": "assets/covers/hybrid/catalog/xevious.webp",
  "Yoshi": "assets/covers/hybrid/catalog/yoshi.webp",
  "Zelda II: The Adventure of Link": "assets/covers/hybrid/catalog/zelda-ii-the-adventure-of-link.webp",
  "Amazing Hebereke": "assets/covers/hybrid/catalog/amazing-hebereke.webp",
  "Battletoads in Battlemaniacs": "assets/covers/hybrid/catalog/battletoads-in-battlemaniacs.webp",
  "Battletoads/Double Dragon": "assets/covers/hybrid/catalog/battletoads-double-dragon.webp",
  "Big Run": "assets/covers/hybrid/catalog/big-run.webp",
  "Bombuzal": "assets/covers/hybrid/catalog/bombuzal.webp",
  "Brawl Brothers": "assets/covers/hybrid/catalog/brawl-brothers.webp",
  "Breath of Fire": "assets/covers/hybrid/catalog/breath-of-fire.webp",
  "Breath of Fire II": "assets/covers/hybrid/catalog/breath-of-fire-ii.webp",
  "Bubsy in Claws Encounters of the Furred Kind": "assets/covers/hybrid/catalog/bubsy-in-claws-encounters-of-the-furred-kind.webp",
  "Claymates": "assets/covers/hybrid/catalog/claymates.webp",
  "Congo's Caper": "assets/covers/hybrid/catalog/congo-s-caper.webp",
  "Cosmo Gang the Puzzle": "assets/covers/hybrid/catalog/cosmo-gang-the-puzzle.webp",
  "Demon's Crest": "assets/covers/hybrid/catalog/demon-s-crest.webp",
  "Donkey Kong Country": "assets/covers/hybrid/catalog/donkey-kong-country.webp",
  "Donkey Kong Country 2: Diddy's Kong Quest": "assets/covers/hybrid/catalog/donkey-kong-country-2-diddy-s-kong-quest.webp",
  "Donkey Kong Country 3: Dixie Kong's Double Trouble!": "assets/covers/hybrid/catalog/donkey-kong-country-3-dixie-kong-s-double-trouble.webp",
  "Doomsday Warrior": "assets/covers/hybrid/catalog/doomsday-warrior.webp",
  "EarthBound": "assets/covers/hybrid/catalog/earthbound.webp",
  "Earthworm Jim 2": "assets/covers/hybrid/catalog/earthworm-jim-2.webp",
  "F-Zero": "assets/covers/hybrid/catalog/f-zero.webp",
  "Fatal Fury 2": "assets/covers/hybrid/catalog/fatal-fury-2.webp",
  "Fatal Fury Special": "assets/covers/hybrid/catalog/fatal-fury-special.webp",
  "Fighter's History": "assets/covers/hybrid/catalog/fighter-s-history.webp",
  "Harvest Moon": "assets/covers/hybrid/catalog/harvest-moon.webp",
  "Jelly Boy": "assets/covers/hybrid/catalog/jelly-boy.webp",
  "Joe & Mac": "assets/covers/hybrid/catalog/joe-mac.webp",
  "Joe & Mac 2: Lost in the Tropics": "assets/covers/hybrid/catalog/joe-mac-2-lost-in-the-tropics.webp",
  "Killer Instinct": "assets/covers/hybrid/catalog/killer-instinct.webp",
  "Kirby Super Star": "assets/covers/hybrid/catalog/kirby-super-star.webp",
  "Kirby's Avalanche": "assets/covers/hybrid/catalog/kirby-s-avalanche.webp",
  "Kirby's Dream Course": "assets/covers/hybrid/catalog/kirby-s-dream-course.webp",
  "Kirby's Dream Land 3": "assets/covers/hybrid/catalog/kirby-s-dream-land-3.webp",
  "Kirby's Star Stacker": "assets/covers/hybrid/catalog/kirby-s-star-stacker.webp",
  "Kunio-kun no Dodgeball da yo Zen'in Shūgō!": "assets/covers/hybrid/catalog/kunio-kun-no-dodgeball-da-yo-zen-in-shugo.webp",
  "Magical Drop II": "assets/covers/hybrid/catalog/magical-drop-ii.webp",
  "Mario & Wario": "assets/covers/hybrid/catalog/mario-wario.webp",
  "Mario Paint": "assets/covers/hybrid/catalog/mario-paint.webp",
  "Mario's Super Picross": "assets/covers/hybrid/catalog/mario-s-super-picross.webp",
  "Natsume Championship Wrestling": "assets/covers/hybrid/catalog/natsume-championship-wrestling.webp",
  "Nobunaga's Ambition": "assets/covers/hybrid/catalog/nobunaga-s-ambition.webp",
  "Nobunaga's Ambition: Lord of Darkness": "assets/covers/hybrid/catalog/nobunaga-s-ambition-lord-of-darkness.webp",
  "Operation Logic Bomb": "assets/covers/hybrid/catalog/operation-logic-bomb.webp",
  "Panel de Pon": "assets/covers/hybrid/catalog/panel-de-pon.webp",
  "Pilotwings": "assets/covers/hybrid/catalog/pilotwings.webp",
  "Pop'n TwinBee": "assets/covers/hybrid/catalog/pop-n-twinbee.webp",
  "Prehistorik Man": "assets/covers/hybrid/catalog/prehistorik-man.webp",
  "Psycho Dream": "assets/covers/hybrid/catalog/psycho-dream.webp",
  "Rival Turf!": "assets/covers/hybrid/catalog/rival-turf.webp",
  "Romance of the Three Kingdoms IV: Wall of Fire": "assets/covers/hybrid/catalog/romance-of-the-three-kingdoms-iv-wall-of-fire.webp",
  "Side Pocket": "assets/covers/hybrid/catalog/side-pocket.webp",
  "Smash Tennis": "assets/covers/hybrid/catalog/smash-tennis.webp",
  "Spanky's Quest": "assets/covers/hybrid/catalog/spanky-s-quest.webp",
  "Star Fox": "assets/covers/hybrid/catalog/star-fox.webp",
  "Star Fox 2": "assets/covers/hybrid/catalog/star-fox-2.webp",
  "Stunt Race FX": "assets/covers/hybrid/catalog/stunt-race-fx.webp",
  "Super Baseball Simulator 1.000": "assets/covers/hybrid/catalog/super-baseball-simulator-1-000.webp",
  "Super E.D.F. Earth Defense Force": "assets/covers/hybrid/catalog/super-e-d-f-earth-defense-force.webp",
  "Super Ghouls 'n Ghosts": "assets/covers/hybrid/catalog/super-ghouls-n-ghosts.webp",
  "Super Mario All-Stars": "assets/covers/hybrid/catalog/super-mario-all-stars.webp",
  "Super Mario Kart": "assets/covers/hybrid/catalog/super-mario-kart.webp",
  "Super Mario World": "assets/covers/hybrid/catalog/super-mario-world.webp",
  "Super Mario World 2: Yoshi's Island": "assets/covers/hybrid/catalog/super-mario-world-2-yoshi-s-island.webp",
  "Super Metroid": "assets/covers/hybrid/catalog/super-metroid.webp",
  "Super Ninja Boy": "assets/covers/hybrid/catalog/super-ninja-boy.webp",
  "Super Punch-Out!!": "assets/covers/hybrid/catalog/super-punch-out.webp",
  "Super Puyo Puyo 2": "assets/covers/hybrid/catalog/super-puyo-puyo-2.webp",
  "Super R-Type": "assets/covers/hybrid/catalog/super-r-type.webp",
  "Super Tennis": "assets/covers/hybrid/catalog/super-tennis.webp",
  "Super Valis IV": "assets/covers/hybrid/catalog/super-valis-iv.webp",
  "Sutte Hakkun": "assets/covers/hybrid/catalog/sutte-hakkun.webp",
  "The Ignition Factor": "assets/covers/hybrid/catalog/the-ignition-factor.webp",
  "The Legend of Zelda: A Link to the Past": "assets/covers/hybrid/catalog/the-legend-of-zelda-a-link-to-the-past.webp",
  "The Peace Keepers": "assets/covers/hybrid/catalog/the-peace-keepers.webp",
  "Tuff E Nuff": "assets/covers/hybrid/catalog/tuff-e-nuff.webp",
  "Uncharted Waters: New Horizons": "assets/covers/hybrid/catalog/uncharted-waters-new-horizons.webp",
  "Wild Guns": "assets/covers/hybrid/catalog/wild-guns.webp",
  "Wrecking Crew '98": "assets/covers/hybrid/catalog/wrecking-crew-98.webp",
  "Alleyway": "assets/covers/hybrid/catalog/alleyway.webp",
  "Alone in the Dark: The New Nightmare": "assets/covers/hybrid/catalog/alone-in-the-dark-the-new-nightmare.webp",
  "Balloon Kid": "assets/covers/hybrid/catalog/balloon-kid.webp",
  "Bionic Commando": "assets/covers/hybrid/catalog/bionic-commando.webp",
  "Blaster Master: Enemy Below": "assets/covers/hybrid/catalog/blaster-master-enemy-below.webp",
  "BurgerTime Deluxe": "assets/covers/hybrid/catalog/burgertime-deluxe.webp",
  "Castlevania Legends": "assets/covers/hybrid/catalog/castlevania-legends.webp",
  "Donkey Kong Land": "assets/covers/hybrid/catalog/donkey-kong-land.webp",
  "Donkey Kong Land 2": "assets/covers/hybrid/catalog/donkey-kong-land-2.webp",
  "Donkey Kong Land III": "assets/covers/hybrid/catalog/donkey-kong-land-iii.webp",
  "Fortified Zone": "assets/covers/hybrid/catalog/fortified-zone.webp",
  "Game & Watch Gallery 3": "assets/covers/hybrid/catalog/game-watch-gallery-3.webp",
  "Gargoyle's Quest": "assets/covers/hybrid/catalog/gargoyle-s-quest.webp",
  "Gradius: The Interstellar Assault": "assets/covers/hybrid/catalog/gradius-the-interstellar-assault.webp",
  "Kid Icarus: Of Myths and Monsters": "assets/covers/hybrid/catalog/kid-icarus-of-myths-and-monsters.webp",
  "Kirby Tilt 'n' Tumble": "assets/covers/hybrid/catalog/kirby-tilt-n-tumble.webp",
  "Kirby's Dream Land": "assets/covers/hybrid/catalog/kirby-s-dream-land.webp",
  "Kirby's Dream Land 2": "assets/covers/hybrid/catalog/kirby-s-dream-land-2.webp",
  "Mario Golf": "assets/covers/hybrid/catalog/mario-golf.webp",
  "Mario Tennis": "assets/covers/hybrid/catalog/mario-tennis.webp",
  "Mario's Picross": "assets/covers/hybrid/catalog/mario-s-picross.webp",
  "Mega Man II": "assets/covers/hybrid/catalog/mega-man-ii.webp",
  "Mega Man III": "assets/covers/hybrid/catalog/mega-man-iii.webp",
  "Mega Man IV": "assets/covers/hybrid/catalog/mega-man-iv.webp",
  "Mega Man V": "assets/covers/hybrid/catalog/mega-man-v.webp",
  "Mega Man: Dr. Wily's Revenge": "assets/covers/hybrid/catalog/mega-man-dr-wily-s-revenge.webp",
  "Metroid II: Return of Samus": "assets/covers/hybrid/catalog/metroid-ii-return-of-samus.webp",
  "Pokémon Trading Card Game": "assets/covers/hybrid/catalog/pokemon-trading-card-game.webp",
  "Quest for Camelot": "assets/covers/hybrid/catalog/quest-for-camelot.webp",
  "Super Mario Land": "assets/covers/hybrid/catalog/super-mario-land.webp",
  "Super Mario Land 2: 6 Golden Coins": "assets/covers/hybrid/catalog/super-mario-land-2-6-golden-coins.webp",
  "Survival Kids": "assets/covers/hybrid/catalog/survival-kids.webp",
  "Tetris DX": "assets/covers/hybrid/catalog/tetris-dx.webp",
  "The Legend of Zelda: Link's Awakening DX": "assets/covers/hybrid/catalog/the-legend-of-zelda-link-s-awakening-dx.webp",
  "The Legend of Zelda: Oracle of Ages": "assets/covers/hybrid/catalog/the-legend-of-zelda-oracle-of-ages.webp",
  "The Legend of Zelda: Oracle of Seasons": "assets/covers/hybrid/catalog/the-legend-of-zelda-oracle-of-seasons.webp",
  "The Sword of Hope": "assets/covers/hybrid/catalog/the-sword-of-hope.webp",
  "The Sword of Hope II": "assets/covers/hybrid/catalog/the-sword-of-hope-ii.webp",
  "Wario Land 3": "assets/covers/hybrid/catalog/wario-land-3.webp",
  "Wario Land: Super Mario Land 3": "assets/covers/hybrid/catalog/wario-land-super-mario-land-3.webp",
  "1080° Snowboarding": "assets/covers/hybrid/catalog/1080-snowboarding.webp",
  "Banjo-Kazooie": "assets/covers/hybrid/catalog/banjo-kazooie.webp",
  "Banjo-Tooie": "assets/covers/hybrid/catalog/banjo-tooie.webp",
  "Blast Corps": "assets/covers/hybrid/catalog/blast-corps.webp",
  "Donkey Kong 64": "assets/covers/hybrid/catalog/donkey-kong-64.webp",
  "Dr. Mario 64": "assets/covers/hybrid/catalog/dr-mario-64.webp",
  "Excitebike 64": "assets/covers/hybrid/catalog/excitebike-64.webp",
  "Extreme-G": "assets/covers/hybrid/catalog/extreme-g.webp",
  "F-Zero X": "assets/covers/hybrid/catalog/f-zero-x.webp",
  "Forsaken 64": "assets/covers/hybrid/catalog/forsaken-64.webp",
  "GoldenEye 007": "assets/covers/hybrid/catalog/goldeneye-007.webp",
  "Harvest Moon 64": "assets/covers/hybrid/catalog/harvest-moon-64.webp",
  "Iggy's Reckin' Balls": "assets/covers/hybrid/catalog/iggy-s-reckin-balls.webp",
  "Jet Force Gemini": "assets/covers/hybrid/catalog/jet-force-gemini.webp",
  "Killer Instinct Gold": "assets/covers/hybrid/catalog/killer-instinct-gold.webp",
  "Kirby 64: The Crystal Shards": "assets/covers/hybrid/catalog/kirby-64-the-crystal-shards.webp",
  "Mario Kart 64": "assets/covers/hybrid/catalog/mario-kart-64.webp",
  "Mario Party": "assets/covers/hybrid/catalog/mario-party.webp",
  "Mario Party 2": "assets/covers/hybrid/catalog/mario-party-2.webp",
  "Mario Party 3": "assets/covers/hybrid/catalog/mario-party-3.webp",
  "Paper Mario": "assets/covers/hybrid/catalog/paper-mario.webp",
  "Perfect Dark": "assets/covers/hybrid/catalog/perfect-dark.webp",
  "Pilotwings 64": "assets/covers/hybrid/catalog/pilotwings-64.webp",
  "Pokémon Puzzle League": "assets/covers/hybrid/catalog/pokemon-puzzle-league.webp",
  "Pokémon Snap": "assets/covers/hybrid/catalog/pokemon-snap.webp",
  "Pokémon Stadium": "assets/covers/hybrid/catalog/pokemon-stadium.webp",
  "Pokémon Stadium 2": "assets/covers/hybrid/catalog/pokemon-stadium-2.webp",
  "Rayman 2: The Great Escape": "assets/covers/hybrid/catalog/rayman-2-the-great-escape.webp",
  "Ridge Racer 64": "assets/covers/hybrid/catalog/ridge-racer-64.webp",
  "Shadow Man": "assets/covers/hybrid/catalog/shadow-man.webp",
  "Sin and Punishment": "assets/covers/hybrid/catalog/sin-and-punishment.webp",
  "Star Fox 64": "assets/covers/hybrid/catalog/star-fox-64.webp",
  "The Legend of Zelda: Majora's Mask": "assets/covers/hybrid/catalog/the-legend-of-zelda-majora-s-mask.webp",
  "The Legend of Zelda: Ocarina of Time": "assets/covers/hybrid/catalog/the-legend-of-zelda-ocarina-of-time.webp",
  "Tonic Trouble": "assets/covers/hybrid/catalog/tonic-trouble.webp",
  "Turok 2: Seeds of Evil": "assets/covers/hybrid/catalog/turok-2-seeds-of-evil.webp",
  "Turok: Dinosaur Hunter": "assets/covers/hybrid/catalog/turok-dinosaur-hunter.webp",
  "Wave Race 64": "assets/covers/hybrid/catalog/wave-race-64.webp",
  "WinBack": "assets/covers/hybrid/catalog/winback.webp",
  "Yoshi's Story": "assets/covers/hybrid/catalog/yoshi-s-story.webp",
  "Densetsu no Starfy": "assets/covers/hybrid/catalog/densetsu-no-starfy.webp",
  "Densetsu no Starfy 2": "assets/covers/hybrid/catalog/densetsu-no-starfy-2.webp",
  "Densetsu no Starfy 3": "assets/covers/hybrid/catalog/densetsu-no-starfy-3.webp",
  "Dr. Mario & Puzzle League": "assets/covers/hybrid/catalog/dr-mario-puzzle-league.webp",
  "F-Zero Climax": "assets/covers/hybrid/catalog/f-zero-climax.webp",
  "F-Zero: GP Legend": "assets/covers/hybrid/catalog/f-zero-gp-legend.webp",
  "F-Zero: Maximum Velocity": "assets/covers/hybrid/catalog/f-zero-maximum-velocity.webp",
  "Fire Emblem: The Blazing Blade": "assets/covers/hybrid/catalog/fire-emblem-the-blazing-blade.webp",
  "Fire Emblem: The Sacred Stones": "assets/covers/hybrid/catalog/fire-emblem-the-sacred-stones.webp",
  "Golden Sun": "assets/covers/hybrid/catalog/golden-sun.webp",
  "Golden Sun: The Lost Age": "assets/covers/hybrid/catalog/golden-sun-the-lost-age.webp",
  "Kirby & the Amazing Mirror": "assets/covers/hybrid/catalog/kirby-the-amazing-mirror.webp",
  "Klonoa: Empire of Dreams": "assets/covers/hybrid/catalog/klonoa-empire-of-dreams.webp",
  "Kuru Kuru Kururin": "assets/covers/hybrid/catalog/kuru-kuru-kururin.webp",
  "Mario & Luigi: Superstar Saga": "assets/covers/hybrid/catalog/mario-luigi-superstar-saga.webp",
  "Mario Kart: Super Circuit": "assets/covers/hybrid/catalog/mario-kart-super-circuit.webp",
  "Mario vs. Donkey Kong": "assets/covers/hybrid/catalog/mario-vs-donkey-kong.webp",
  "Metroid Fusion": "assets/covers/hybrid/catalog/metroid-fusion.webp",
  "Metroid: Zero Mission": "assets/covers/hybrid/catalog/metroid-zero-mission.webp",
  "Mr. Driller 2": "assets/covers/hybrid/catalog/mr-driller-2.webp",
  "Pokémon Mystery Dungeon: Red Rescue Team": "assets/covers/hybrid/catalog/pokemon-mystery-dungeon-red-rescue-team.webp",
  "Super Mario Advance": "assets/covers/hybrid/catalog/super-mario-advance.webp",
  "Super Mario Advance 4: Super Mario Bros. 3": "assets/covers/hybrid/catalog/super-mario-advance-4-super-mario-bros-3.webp",
  "Super Mario World: Super Mario Advance 2": "assets/covers/hybrid/catalog/super-mario-world-super-mario-advance-2.webp",
  "The Legend of Zelda: A Link to the Past and Four Swords": "assets/covers/hybrid/catalog/the-legend-of-zelda-a-link-to-the-past-and-four-swords.webp",
  "The Legend of Zelda: The Minish Cap": "assets/covers/hybrid/catalog/the-legend-of-zelda-the-minish-cap.webp",
  "Wario Land 4": "assets/covers/hybrid/catalog/wario-land-4.webp",
  "WarioWare, Inc.: Mega Microgames!": "assets/covers/hybrid/catalog/warioware-inc-mega-microgames.webp",
  "Yoshi's Island: Super Mario Advance 3": "assets/covers/hybrid/catalog/yoshi-s-island-super-mario-advance-3.webp",
  "Alien Soldier": "assets/covers/hybrid/catalog/alien-soldier.webp",
  "Alien Storm": "assets/covers/hybrid/catalog/alien-storm.webp",
  "Alisia Dragoon": "assets/covers/hybrid/catalog/alisia-dragoon.webp",
  "Altered Beast": "assets/covers/hybrid/catalog/altered-beast.webp",
  "Beyond Oasis": "assets/covers/hybrid/catalog/beyond-oasis.webp",
  "Castlevania: Bloodlines": "assets/covers/hybrid/catalog/castlevania-bloodlines.webp",
  "Columns": "assets/covers/hybrid/catalog/columns.webp",
  "Comix Zone": "assets/covers/hybrid/catalog/comix-zone.webp",
  "Contra: Hard Corps": "assets/covers/hybrid/catalog/contra-hard-corps.webp",
  "Crusader of Centy": "assets/covers/hybrid/catalog/crusader-of-centy.webp",
  "Dr. Robotnik's Mean Bean Machine": "assets/covers/hybrid/catalog/dr-robotnik-s-mean-bean-machine.webp",
  "Dynamite Headdy": "assets/covers/hybrid/catalog/dynamite-headdy.webp",
  "Earthworm Jim": "assets/covers/hybrid/catalog/earthworm-jim-generated.webp",
  "Ecco the Dolphin": "assets/covers/hybrid/catalog/ecco-the-dolphin.webp",
  "ESWAT: City Under Siege": "assets/covers/hybrid/catalog/eswat-city-under-siege.webp",
  "Flicky": "assets/covers/hybrid/catalog/flicky.webp",
  "Ghouls 'n Ghosts": "assets/covers/hybrid/catalog/ghouls-n-ghosts.webp",
  "Golden Axe": "assets/covers/hybrid/catalog/golden-axe.webp",
  "Golden Axe II": "assets/covers/hybrid/catalog/golden-axe-ii.webp",
  "Gunstar Heroes": "assets/covers/hybrid/catalog/gunstar-heroes.webp",
  "Kid Chameleon": "assets/covers/hybrid/catalog/kid-chameleon.webp",
  "Landstalker": "assets/covers/hybrid/catalog/landstalker.webp",
  "Light Crusader": "assets/covers/hybrid/catalog/light-crusader.webp",
  "Mega Man: The Wily Wars": "assets/covers/hybrid/catalog/mega-man-the-wily-wars.webp",
  "Mercs": "assets/covers/hybrid/catalog/mercs.webp",
  "MUSHA": "assets/covers/hybrid/catalog/musha.webp",
  "Phantasy Star IV": "assets/covers/hybrid/catalog/phantasy-star-iv.webp",
  "Pulseman": "assets/covers/hybrid/catalog/pulseman.webp",
  "Ristar": "assets/covers/hybrid/catalog/ristar.webp",
  "Shining Force": "assets/covers/hybrid/catalog/shining-force.webp",
  "Shining Force II": "assets/covers/hybrid/catalog/shining-force-ii.webp",
  "Shinobi III: Return of the Ninja Master": "assets/covers/hybrid/catalog/shinobi-iii-return-of-the-ninja-master.webp",
  "Sonic Spinball": "assets/covers/hybrid/catalog/sonic-spinball.webp",
  "Sonic the Hedgehog 2": "assets/covers/hybrid/catalog/sonic-the-hedgehog-2.webp",
  "Space Harrier II": "assets/covers/hybrid/catalog/space-harrier-ii.webp",
  "Street Fighter II': Special Champion Edition": "assets/covers/hybrid/catalog/street-fighter-ii-special-champion-edition.webp",
  "Streets of Rage": "assets/covers/hybrid/catalog/streets-of-rage.webp",
  "Streets of Rage 2": "assets/covers/hybrid/catalog/streets-of-rage-2.webp",
  "Strider": "assets/covers/hybrid/catalog/strider.webp",
  "Super Fantasy Zone": "assets/covers/hybrid/catalog/super-fantasy-zone.webp",
  "Super Thunder Blade": "assets/covers/hybrid/catalog/super-thunder-blade.webp",
  "Sword of Vermilion": "assets/covers/hybrid/catalog/sword-of-vermilion.webp",
  "Target Earth": "assets/covers/hybrid/catalog/target-earth.webp",
  "The Revenge of Shinobi": "assets/covers/hybrid/catalog/the-revenge-of-shinobi.webp",
  "Thunder Force II": "assets/covers/hybrid/catalog/thunder-force-ii.webp",
  "ToeJam & Earl": "assets/covers/hybrid/catalog/toejam-earl.webp",
  "ToeJam & Earl in Panic on Funkotron": "assets/covers/hybrid/catalog/toejam-earl-in-panic-on-funkotron.webp",
  "Vectorman": "assets/covers/hybrid/catalog/vectorman.webp",
  "Virtua Fighter 2": "assets/covers/hybrid/catalog/virtua-fighter-2.webp",
  "Zero Wing": "assets/covers/hybrid/catalog/zero-wing.webp",
  "3D Tetris": "assets/covers/hybrid/catalog/3d-tetris.webp",
  "Dragon Hopper": "assets/covers/hybrid/catalog/dragon-hopper.webp",
  "Galactic Pinball": "assets/covers/hybrid/catalog/galactic-pinball.webp",
  "Jack Bros.": "assets/covers/hybrid/catalog/jack-bros.webp",
  "Mario Clash": "assets/covers/hybrid/catalog/mario-clash.webp",
  "Mario's Tennis": "assets/covers/hybrid/catalog/mario-s-tennis.webp",
  "Red Alarm": "assets/covers/hybrid/catalog/red-alarm.webp",
  "Space Invaders Virtual Collection": "assets/covers/hybrid/catalog/space-invaders-virtual-collection.webp",
  "Teleroboxer": "assets/covers/hybrid/catalog/teleroboxer.webp",
  "The Mansion of Innsmouth": "assets/covers/hybrid/catalog/the-mansion-of-innsmouth.webp",
  "V-Tetris": "assets/covers/hybrid/catalog/v-tetris.webp",
  "Vertical Force": "assets/covers/hybrid/catalog/vertical-force.webp",
  "Virtual Bowling": "assets/covers/hybrid/catalog/virtual-bowling.webp",
  "Virtual Boy Wario Land": "assets/covers/hybrid/catalog/virtual-boy-wario-land.webp",
  "Zero Racers": "assets/covers/hybrid/catalog/zero-racers.webp",
  "Chibi-Robo!": "assets/covers/hybrid/catalog/chibi-robo-generated.webp",
  "F-Zero GX": "assets/covers/hybrid/catalog/f-zero-gx-generated.webp",
  "Fire Emblem: Path of Radiance": "assets/covers/hybrid/catalog/fire-emblem-path-of-radiance-user-generated.webp",
  "Luigi's Mansion": "assets/covers/hybrid/catalog/luigis-mansion-user-generated.webp",
  "Pokémon XD: Gale of Darkness": "assets/covers/hybrid/catalog/pokemon-xd-gale-of-darkness-user-generated.webp",
  "Soulcalibur II": "assets/covers/hybrid/catalog/soulcalibur-ii-generated.webp",
  "Super Mario Strikers": "assets/covers/hybrid/catalog/super-mario-strikers-generated.webp",
  "The Legend of Zelda: The Wind Waker": "assets/covers/hybrid/catalog/zelda-wind-waker-woodblock-solo-full-title-generated.webp",
  "Wario World": "assets/covers/hybrid/catalog/wario-world-user-generated.webp",
  "Assassin's Creed Valhalla": "assets/covers/hybrid/catalog/assassin-s-creed-valhalla.webp",
  "CRISIS CORE -FINAL FANTASY VII- REUNION": "assets/covers/hybrid/catalog/crisis-core-final-fantasy-vii-reunion.webp",
  "Dead Space": "assets/covers/hybrid/catalog/dead-space.webp",
  "Destiny 2": "assets/covers/hybrid/catalog/destiny-2.webp",
  "DRAGON BALL Z: KAKAROT": "assets/covers/hybrid/catalog/dragon-ball-z-kakarot.webp",
  "FINAL FANTASY VII REBIRTH": "assets/covers/hybrid/catalog/final-fantasy-vii-rebirth.webp",
  "FINAL FANTASY VII REMAKE": "assets/covers/hybrid/catalog/final-fantasy-vii-remake.webp",
  "FINAL FANTASY XIV Online": "assets/covers/hybrid/catalog/final-fantasy-xiv-online.webp",
  "FINAL FANTASY XVI": "assets/covers/hybrid/catalog/final-fantasy-xvi.webp",
  "Ghost of Tsushima": "assets/covers/hybrid/catalog/ghost-of-tsushima.webp",
  "Hood: Outlaws & Legends": "assets/covers/hybrid/catalog/hood-outlaws-legends.webp",
  "Horizon Forbidden West Digital Deluxe": "assets/covers/hybrid/catalog/horizon-forbidden-west-digital-deluxe.webp",
  "Marvel's Spider-Man Remastered": "assets/covers/hybrid/catalog/marvel-s-spider-man-remastered.webp",
  "OUTRIDERS": "assets/covers/hybrid/catalog/outriders.webp",
  "Ratchet & Clank: Rift Apart Digital Deluxe Edition": "assets/covers/hybrid/catalog/ratchet-clank-rift-apart-digital-deluxe-edition.webp",
  "Resident Evil 4": "assets/covers/hybrid/catalog/resident-evil-4.webp",
  "Sonic Frontiers": "assets/covers/hybrid/catalog/sonic-frontiers.webp",
  "STRANGER OF PARADISE FINAL FANTASY ORIGIN": "assets/covers/hybrid/catalog/stranger-of-paradise-final-fantasy-origin.webp",
  "The Callisto Protocol": "assets/covers/hybrid/catalog/the-callisto-protocol.webp",
  "The First Descendant": "assets/covers/hybrid/catalog/the-first-descendant.webp",
  "The Last of Us Part I": "assets/covers/hybrid/catalog/the-last-of-us-part-i.webp",
  "The Legend of Dragoon": "assets/covers/hybrid/catalog/the-legend-of-dragoon.webp",
  "Agents of Mayhem": "assets/covers/hybrid/catalog/agents-of-mayhem.webp",
  "Apex Legends": "assets/covers/hybrid/catalog/apex-legends.webp",
  "Batman: Arkham Knight": "assets/covers/hybrid/catalog/batman-arkham-knight.webp",
  "Batman: Return to Arkham - Arkham Asylum": "assets/covers/hybrid/catalog/batman-return-to-arkham-arkham-asylum.webp",
  "Batman: Return to Arkham - Arkham City": "assets/covers/hybrid/catalog/batman-return-to-arkham-arkham-city.webp",
  "Battle Chasers: Nightwar": "assets/covers/hybrid/catalog/battle-chasers-nightwar.webp",
  "Blacklight: Retribution": "assets/covers/hybrid/catalog/blacklight-retribution.webp",
  "Bleach: Brave Souls": "assets/covers/hybrid/catalog/bleach-brave-souls.webp",
  "Bloodborne": "assets/covers/hybrid/catalog/bloodborne.webp",
  "Dark Cloud": "assets/covers/hybrid/catalog/dark-cloud.webp",
  "Dark Cloud 2": "assets/covers/hybrid/catalog/dark-cloud-2.webp",
  "Dark Souls III": "assets/covers/hybrid/catalog/dark-souls-iii.webp",
  "Darksiders II Deathinitive Edition": "assets/covers/hybrid/catalog/darksiders-ii-deathinitive-edition.webp",
  "Destiny": "assets/covers/hybrid/catalog/destiny.webp",
  "Diablo III: Reaper of Souls - Ultimate Evil Edition": "assets/covers/hybrid/catalog/diablo-iii-reaper-of-souls-ultimate-evil-edition.webp",
  "DOOM Eternal": "assets/covers/hybrid/catalog/doom-eternal.webp",
  "Dragon's Crown Pro": "assets/covers/hybrid/catalog/dragon-s-crown-pro.webp",
  "Dragon's Dogma: Dark Arisen": "assets/covers/hybrid/catalog/dragon-s-dogma-dark-arisen.webp",
  "FINAL FANTASY XV": "assets/covers/hybrid/catalog/final-fantasy-xv.webp",
  "For Honor": "assets/covers/hybrid/catalog/for-honor.webp",
  "Fortnite": "assets/covers/hybrid/catalog/fortnite.webp",
  "Grand Kingdom": "assets/covers/hybrid/catalog/grand-kingdom.webp",
  "Horizon Zero Dawn": "assets/covers/hybrid/catalog/horizon-zero-dawn.webp",
  "Injustice: Gods Among Us Ultimate Edition": "assets/covers/hybrid/catalog/injustice-gods-among-us-ultimate-edition.webp",
  "KINGDOM HEARTS - HD 1.5+2.5 ReMIX -": "assets/covers/hybrid/catalog/kingdom-hearts-hd-1-5-2-5-remix.webp",
  "KINGDOM HEARTS HD 2.8 FINAL CHAPTER PROLOGUE": "assets/covers/hybrid/catalog/kingdom-hearts-hd-2-8-final-chapter-prologue.webp",
  "Knack 2": "assets/covers/hybrid/catalog/knack-2.webp",
  "LEGO Marvel Super Heroes 2": "assets/covers/hybrid/catalog/lego-marvel-super-heroes-2.webp",
  "Lords of the Fallen": "assets/covers/hybrid/catalog/lords-of-the-fallen.webp",
  "Mega Man X Legacy Collection": "assets/covers/hybrid/catalog/mega-man-x-legacy-collection.webp",
  "Mega Man X Legacy Collection 2": "assets/covers/hybrid/catalog/mega-man-x-legacy-collection-2.webp",
  "Metro 2033 Redux": "assets/covers/hybrid/catalog/metro-2033-redux.webp",
  "Middle-earth: Shadow of Mordor": "assets/covers/hybrid/catalog/middle-earth-shadow-of-mordor.webp",
  "Monster Hunter World: Iceborne": "assets/covers/hybrid/catalog/monster-hunter-world-iceborne.webp",
  "Neverwinter": "assets/covers/hybrid/catalog/neverwinter.webp",
  "Nioh: Complete Edition": "assets/covers/hybrid/catalog/nioh-complete-edition.webp",
  "ONE PIECE: PIRATE WARRIORS 3": "assets/covers/hybrid/catalog/one-piece-pirate-warriors-3.webp",
  "Onigiri": "assets/covers/hybrid/catalog/onigiri.webp",
  "Overwatch": "assets/covers/hybrid/catalog/overwatch.webp",
  "Paragon": "assets/covers/hybrid/catalog/paragon.webp",
  "Phantasy Star Online 2 New Genesis": "assets/covers/hybrid/catalog/phantasy-star-online-2-new-genesis.webp",
  "Pillars of Eternity: Complete Edition": "assets/covers/hybrid/catalog/pillars-of-eternity-complete-edition.webp",
  "Psychonauts in the Rhombus of Ruin": "assets/covers/hybrid/catalog/psychonauts-in-the-rhombus-of-ruin.webp",
  "Resident Evil 2": "assets/covers/hybrid/catalog/resident-evil-2.webp",
  "Resident Evil 3": "assets/covers/hybrid/catalog/resident-evil-3.webp",
  "Resident Evil 5": "assets/covers/hybrid/catalog/resident-evil-5.webp",
  "Resident Evil 6": "assets/covers/hybrid/catalog/resident-evil-6.webp",
  "Resident Evil Resistance": "assets/covers/hybrid/catalog/resident-evil-resistance.webp",
  "SMITE": "assets/covers/hybrid/catalog/smite.webp",
  "STAR OCEAN: Integrity and Faithlessness": "assets/covers/hybrid/catalog/star-ocean-integrity-and-faithlessness.webp",
  "Star Wars Battlefront II": "assets/covers/hybrid/catalog/star-wars-battlefront-ii.webp",
  "TERA": "assets/covers/hybrid/catalog/tera.webp",
  "Terraria": "assets/covers/hybrid/catalog/terraria.webp",
  "The Last of Us Part II": "assets/covers/hybrid/catalog/the-last-of-us-part-ii.webp",
  "The Last of Us Remastered": "assets/covers/hybrid/catalog/the-last-of-us-remastered.webp",
  "Tom Clancy's Ghost Recon Wildlands": "assets/covers/hybrid/catalog/tom-clancy-s-ghost-recon-wildlands.webp",
  "Tom Clancy's Rainbow Six Siege": "assets/covers/hybrid/catalog/tom-clancy-s-rainbow-six-siege.webp",
  "Tom Clancy's The Division": "assets/covers/hybrid/catalog/tom-clancy-s-the-division.webp",
  "Warframe": "assets/covers/hybrid/catalog/warframe.webp",
  "Ys VIII: Lacrimosa of Dana": "assets/covers/hybrid/catalog/ys-viii-lacrimosa-of-dana.webp",
  "Chrono Trigger": "assets/covers/hybrid/catalog/chrono-trigger.webp",
  "Contra III: The Alien Wars": "assets/covers/hybrid/catalog/contra-iii-the-alien-wars-generated.webp",
  "Doom": "assets/covers/hybrid/catalog/doom-generated.webp",
  "Final Fantasy II": "assets/covers/hybrid/catalog/final-fantasy-ii-generated.webp",
  "Final Fantasy III": "assets/covers/hybrid/catalog/final-fantasy-iii-generated.webp",
  "Final Fantasy: Mystic Quest": "assets/covers/hybrid/catalog/final-fantasy-mystic-quest-generated.webp",
  "Illusion of Gaia": "assets/covers/hybrid/catalog/illusion-of-gaia-generated.webp",
  "Judge Dredd": "assets/covers/hybrid/catalog/judge-dredd-generated.webp",
  "Lufia & the Fortress of Doom": "assets/covers/hybrid/catalog/lufia-the-fortress-of-doom-generated.webp",
  "Lufia II: Rise of the Sinistrals": "assets/covers/hybrid/catalog/lufia-ii-rise-of-the-sinistrals-generated.webp",
  "Mega Man 7": "assets/covers/hybrid/catalog/mega-man-7-generated.webp",
  "Mega Man Soccer": "assets/covers/hybrid/catalog/mega-man-soccer.webp",
  "Mega Man X": "assets/covers/hybrid/catalog/mega-man-x.webp",
  "Mega Man X2": "assets/covers/hybrid/catalog/mega-man-x2.webp",
  "Mega Man X3": "assets/covers/hybrid/catalog/mega-man-x3.webp",
  "Secret of Evermore": "assets/covers/hybrid/catalog/secret-of-evermore.webp",
  "Secret of Mana": "assets/covers/hybrid/catalog/secret-of-mana.webp",
  "Soul Blazer": "assets/covers/hybrid/catalog/soul-blazer.webp",
  "Sparkster": "assets/covers/hybrid/catalog/sparkster.webp",
  "Super Mario RPG: Legend of the Seven Stars": "assets/covers/hybrid/catalog/super-mario-rpg-legend-of-the-seven-stars.webp",
  "SWAT Kats: The Radical Squadron": "assets/covers/hybrid/catalog/swat-kats-the-radical-squadron.webp",
  "Tales of Phantasia": "assets/covers/hybrid/catalog/tales-of-phantasia.webp",
  "Teenage Mutant Ninja Turtles IV: Turtles in Time": "assets/covers/hybrid/catalog/teenage-mutant-ninja-turtles-iv-turtles-in-time.webp",
  "Terranigma": "assets/covers/hybrid/catalog/terranigma.webp",
  "Tiny Toon Adventures: Buster Busts Loose!": "assets/covers/hybrid/catalog/tiny-toon-adventures-buster-busts-loose.webp",
  "Tom and Jerry": "assets/covers/hybrid/catalog/tom-and-jerry.webp",
  "Wolverine: Adamantium Rage": "assets/covers/hybrid/catalog/wolverine-adamantium-rage.webp",
  "X-Men: Mutant Apocalypse": "assets/covers/hybrid/catalog/x-men-mutant-apocalypse.webp",
  "Ys III: Wanderers from Ys": "assets/covers/hybrid/catalog/ys-iii-wanderers-from-ys.webp"
});

// The deployed catalog uses compact cover atlases so the full non-PC artwork
// library can be published and cached efficiently. Object key order matches
// the atlas build order below (20 covers per 5-by-4 sheet).
const hybridSpriteCovers = Object.fromEntries(
  Object.keys(window.HYBRID_COVERS).map((title, index) => [
    title,
    `hybrid-sprite:assets/covers/hybrid/atlases/catalog-${String(Math.floor(index / 20) + 1).padStart(2, "0")}.webp:${index % 20}`,
  ]),
);

// Individually generated covers override their legacy atlas slots. Naming new
// files with the `-generated.webp` suffix makes future replacements automatic.
Object.entries(window.HYBRID_COVERS).forEach(([title, coverPath]) => {
  if (coverPath.endsWith("-generated.webp")) hybridSpriteCovers[title] = coverPath;
});

window.HYBRID_SPRITES = Object.freeze(hybridSpriteCovers);
