// Individually generated PS5 key art with titles integrated into each image.
window.PS5_COVERS = Object.freeze({
  "FINAL FANTASY XVI": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:0",
  "Assassin's Creed Valhalla": "assets/covers/ps5/assassins-creed-valhalla.webp",
  "The First Descendant": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:2",
  "FINAL FANTASY VII REBIRTH": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:3",
  "Resident Evil 4": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:4",
  "The Legend of Dragoon": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:5",
  "Dead Space": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:6",
  "DRAGON BALL Z: KAKAROT": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:7",
  "CRISIS CORE -FINAL FANTASY VII- REUNION": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:8",
  "The Callisto Protocol": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:9",
  "Sonic Frontiers": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:10",
  "The Last of Us Part I": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:11",
  "STRANGER OF PARADISE FINAL FANTASY ORIGIN": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:12",
  "Horizon Forbidden West Digital Deluxe": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:13",
  "Destiny 2": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:14",
  "FINAL FANTASY XIV Online": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:15",
  "Ghost of Tsushima": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:16",
  "Ratchet & Clank: Rift Apart Digital Deluxe Edition": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:17",
  "Ruinverse": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:18",
  "Hood: Outlaws & Legends": "hybrid-sprite:assets/covers/ps5/atlases/ps5-01.webp:19",
  "FINAL FANTASY VII REMAKE": "hybrid-sprite:assets/covers/ps5/atlases/ps5-02.webp:0",
  "OUTRIDERS": "hybrid-sprite:assets/covers/ps5/atlases/ps5-02.webp:1",
  "Marvel's Spider-Man Remastered": "hybrid-sprite:assets/covers/ps5/atlases/ps5-02.webp:2",
});
